# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='List', max_length=100)),
                ('color', models.CharField(default='#e5ae72', max_length=10)),
            ],
        ),
    ]
